### ISSUE TITLE
ES for TCGA data

### ISSUE THREAD

**Issue by grubaK** [dviraran/xCell#18]
Hello, 

I am completely new in this topic and I am trying to understand what exactly include TCGA file from  http://xcell.ucsf.edu/. For now, I know that there are enrichment scores (ES) across all TCGA samples for 64 cell types, but are this ES raw scores or adjusted? It is not clear for me how to interpret those results at all. 

In the README you wrote: 

>  the main usage is for comparing across samples, not across cell types

 so can I use those scores to comparing each sample separately? I mean, eg: score for melanocytes for sample X is equal to 0.4 and for sample Y is equal to 0.3. Does it mean that in X sample melanocytes are more enriched? Why I shouldn't compare ES across cell types? If CD8+ T-cells (4.773e-02) have higher ES than CD4+ T-cells (2.485e-18), it is not mean that CD8+ T-cells within the same sample are more enriched? It is very unclear to me. 

Additionally, I noticed that the range of scores across samples is different eg: sample X has from -2.048e-17  to 5.515e-01, and Y has from -1.430e-17 to 1.853e+00. How to interpret those difference? And the last question what do the negative values mean? 

I will be very grateful for your response. 

Best, 
Kasia

**Comment by dviraran** [comment]
Hi,

> I am completely new in this topic and I am trying to understand what exactly include TCGA file from http://xcell.ucsf.edu/. For now, I know that there are enrichment scores (ES) across all TCGA samples for 64 cell types, but are this ES raw scores or adjusted? It is not clear for me how to interpret those results at all.

Yes those are the adjusted xCell scores. 

> so can I use those scores to comparing each sample separately? I mean, eg: score for melanocytes for sample X is equal to 0.4 and for sample Y is equal to 0.3. Does it mean that in X sample melanocytes are more enriched? Why I shouldn't compare ES across cell types? If CD8+ T-cells (4.773e-02) have higher ES than CD4+ T-cells (2.485e-18), it is not mean that CD8+ T-cells within the same sample are more enriched? It is very unclear to me.

Yes, you are understanding it correctly. Because the way xCell was developed it is not reliable for comparing across cell types. Each cell type is independent and because of normalization issues, although the score tries to immitate percentages, it cannot be used as such. 

As I wrote before, I did experiment with comparing cell typeas, and I do believe that in some cases it is comparable, but not in all cases and not cell types.

> Additionally, I noticed that the range of scores across samples is different eg: sample X has from -2.048e-17 to 5.515e-01, and Y has from -1.430e-17 to 1.853e+00. How to interpret those difference? 

Not sure what you mean here. There are differences in the compositions.

> And the last question what do the negative values mean?`

This file is a bit old. The negative values are just a weird output in R. Those should all be zeros (note that all negatives are less than 1e-15 from 0. xCell is of course not accurate enough to detect such small differences. It is best to run something like scores = round(scores*1000)/1000.

Best,
Dvir

**Comment by grubaK** [comment]
Hi, 

Thank you for the response, it is very useful for me. 

Best, 
Kasia
