### ISSUE TITLE
Strange data on datasets with single cell type RNA-seq

### ISSUE THREAD

**Issue by alezanalp** [dviraran/xCell#6]
I've tried to validate xCell on single cell type RNA-seq data and found something strange.
I used two datasets: E-GEOD-77808 with NK cells and E-GEOD-62241 with B cells. MCP counter perform well on them, but xCell gave another cell type as result.

I'm attaching two files (*.info) with the information about these datasets. Also I'm attaching figures with cell type results for these datasets after xCell and MCP-counter. More for xCell I have figures with clustering of cell types, I think it may be usefull for you. 

https://www.dropbox.com/s/hkslhbflew6tkot/E-GEOD-62241.info?dl=0
https://www.dropbox.com/s/ow4yjfpz0d3wht0/E-GEOD-77808.info?dl=0

1. Bcell
**MCP-counter**

![bcell_mcp_v2](https://user-images.githubusercontent.com/22212082/27903057-a0bdc5d2-6240-11e7-9588-f74ed843f96d.png)
**xCell**

![bcell_xcell_v2](https://user-images.githubusercontent.com/22212082/27903061-a0c4569a-6240-11e7-935a-d61688560544.png)
**xCell cluster**

![bcell_xcell_cluster](https://user-images.githubusercontent.com/22212082/27903059-a0c1c75e-6240-11e7-98d4-5df2feecb7d3.png)

2. MCP
**MCP-counter**

![nk_mcp](https://user-images.githubusercontent.com/22212082/27903058-a0bdf430-6240-11e7-9a08-bedd6c64719d.png)
**xCell**

![nk_xcell](https://user-images.githubusercontent.com/22212082/27903056-a0bd2fc8-6240-11e7-8ff2-efdc23d495b3.png)
**xCell cluster**

![nk_xcell_cluster](https://user-images.githubusercontent.com/22212082/27903060-a0c37c0c-6240-11e7-98d7-d293dafe3a2d.png)

**Comment by dviraran** [comment]
Thank you for raising the issue. There numerous problems with the analysis you are presented, and I will try to summarize all of them:

1. xCell produces enrichment scores, not percentages. It is not a deconvolution method, but an enrichment method. That means that the main usage is for comparing across samples, not across cell types. xCell does an attempt to make the scores resemble percentages, but it is a hard problem, and is very platform and experiment specific. We have made some tests to compare the ability of xCell for cross cell types analysis, and found that it generally performed better in that than other methods, but this type of analysis should be performed carefully.

Regarding this issue, scaling the scores by samples is extremely dangerous and will inevitably
will result in false interpretations.

2. For the linear transformation xCell uses a calibration parameter to make it resemble percentages. As you can see in you your analysis, it is clearly wrong for several cell types, where the scores are high although the cell type is clearly not part of the mixture. This is definitely a problem, which as I noted, is a hard problem, mainly because it is platform specific. However, xCell allows you to tweak these parameters. If you see that the smooth muscle scores are too high, you can play with its calibration parameter to lower it. The calibration parameter can be found in the xCell.data object (xCell.data$spill$fv$V3). In the paper, we used an automatic method to learn these parameters, but if you have prior knowledge about your mixture, this is very handy to get better results. 

3. xCell uses the variability among the samples for the linear transformation. If I understand correctly, you did not run xCell for the whole expression matrix, but to small clusters. This will again inevitably result in false results. If there is no variability between the NK cells, xCell will not identify any signal there. xCell will only function with heterogenous mixtures.

4. This leads me to the next point - xCell is a method for detecting cell types enrichments from mixed samples, not to detect the cell of origin. xCell is still able to recognize the cell of origin many times, but it was not trained for this problem, and there is no expectation that it will perform better than other methods for that problem.

This is one of the reasons that is strongly not advised to be performed on single-cell data. There are clearly other methods, that are far more suitable to this problem (I myself have developed one, which will hopefully be public soon). Another reason why this is not advised is that xCell uses gene signatures, and therefore will not perform well with gene drop-outs. Again, other methods have a much better ability to cope with that issue.

5. xCell is different from MCP-counter in its aim. MCP-counter attempts to estimate the proportion of main components of mixed tissues. xCell attempts to go beyond these major subsets and provide a much deeper view of the cellular heterogeneity of the tissue. This depth xCell tries to provide is significantly more complicated, and a such its results may not be as accurate as methods which only tries to provide a broad overview.

I hope I covered the main issues, and hope this helps. I will add these points to the main readme of this GitHub.

Best,
Dvir

**Comment by alezanalp** [comment]
For 3 task you misunderstood me a bit. I ran xCell for whole expression matrix with all samples in one dataset. But, yeah, there was only one cell type, so as you said it was not good data for xCell. 

Thank you for the detailed response!
